trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: DevOps/opsguild.automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

variables:
  - name: analysisProject
    value: Auth-CC_Postman

parameters:
  - name: pool
    default: DevOps Managed Containers Build
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Windows_NT']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    variables:
      - name: 0.TenantId
        value: $(TenantId)
      - name: 0.NamespaceId
        value: $(NamespaceId)
      - name: 0.ClientId
        value: $(ClientId)
      - name: 0.ClientSecret
        value: $(ClientSecret)
      - name: 0.StreamId
        value: $(StreamId)
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, ClientId, ClientSecret, StreamId'

      - script: npm install -g newman
        displayName: 'Install newman'

      - script: npm ci
        displayName: 'Install dependencies'
        
      - script: newman run .\postman_collection.json -d .\appsettings.json --verbose
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)/TestResults'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

